In [ ]:
# numpy.linalg.matrix_power - возведение в степень
# np.matmul - перемножение матриц
# np.transpose - транспонирование

In [1]:
import numpy as np

In [205]:
# Обертка чтобы использовать обычные мат. операнды над numpy матрицами


class Matrix:
    def __init__(self, python_array=None, ndarray=None):
        if python_array:
            self.array = np.array(python_array)
        else:
            self.array = ndarray
    
    def __mul__(self, other):
        return Matrix(ndarray=np.matmul(self.array, other.array))

    def __pow__(self, n):
        return Matrix(ndarray=np.linalg.matrix_power(self.array, n))

    def t(self):
        return Matrix(ndarray=np.transpose(self.array))

    def __str__(self):
        return str(self.array)

    def __repr__(self):
        return repr(self.array)

    def __add__(self, other):
        return Matrix(ndarray=self.array + other.array)

    def as_number(self):
        assert all(map(lambda x: x == 1, self.array.shape)), f'Matrix with shape={self.array.shape} нельзя перевести в число'
        return self.array[0]  # TODO: написать метод нормально
        
    def __iter__(self):
        return iter(self.array)

In [76]:
def count_regression(X, Y):
    """ Y = XB + E, здесь B - искомые коофициенты регрессии, Е - вектор ошибок регрессии """
    return (X.t() * X) ** -1 * X.t() * Y

In [188]:
# Попробуем научится отличать существительные от глаголов
# Обучающая выборка:
nouns = ['книга', 'стол', 'чашка', 'ручка', 'мяч', 'пальто', 'телефон', 'цветок', 'яблоко', 'карандаш', 'столик', 'ковер', 'окно', 'сумка', 'молоко', 'сковорода', 'подушка', 'рубашка', 'ключ', 'лампа', 'кошка', 'собака', 'рыба', 'вода', 'ложка', 'вилка', 'стакан', 'кольцо', 'сапог', 'кепка', 'машина', 'дом', 'кот', 'медведь', 'лестница', 'тарелка', 'сумка', 'платье', 'стена', 'шарф', 'солнце', 'луна', 'звезда', 'столб', 'горшок', 'скатерть', 'шуба', 'гитара', 'подарок', 'дождь', 'ветер', 'гроза', 'песок', 'муравей', 'цветок', 'каша', 'огонь', 'бумага', 'часы', 'браслет', 'чашка', 'кухня', 'мебель', 'почта', 'журнал', 'кошелек', 'зеркало', 'мыло', 'подарок', 'коробка', 'тумблер', 'носки', 'перчатки', 'крем', 'платье', 'белье', 'окно', 'дверь', 'весна', 'лето', 'осень', 'зима', 'медведь', 'волк', 'суслик', 'клоун', 'шоколад', 'часы', 'экран', 'кондиционер', 'телевизор', 'ковер', 'плед', 'гитара', 'виолончель', 'пианино', 'скрипка', 'тромбон', 'утюг', 'кофе']
verbs = ['бежать', 'плавать', 'есть', 'пить', 'читать', 'писать', 'смеяться', 'плакать', 'готовить', 'улыбаться', 'думать', 'говорить', 'слушать', 'танцевать', 'прыгать', 'спать', 'будить', 'петь', 'покупать', 'продавать', 'работать', 'отдыхать', 'спорить', 'обсуждать', 'бороться', 'любить', 'ненавидеть', 'встречать', 'прощаться', 'помогать', 'отказывать', 'мечтать', 'забывать', 'вспоминать', 'смотреть', 'открывать', 'закрывать', 'прятаться', 'находить', 'терять', 'волноваться', 'успокаивать', 'ждать', 'приходить', 'уходить', 'позвонить', 'писать', 'создавать', 'уничтожать', 'строить', 'разрушать', 'рисовать', 'фотографировать', 'поднимать', 'опускать', 'задавать', 'отвечать', 'поддерживать', 'убивать', 'рожать', 'умирать', 'прятать', 'раскрывать', 'открывать', 'скрывать', 'воровать', 'взять', 'отдать', 'дать', 'брать', 'сидеть', 'вставать', 'ходить', 'бежать', 'прыгать', 'падать', 'стрелять', 'ловить', 'бойтись', 'смущать', 'открывать', 'закрывать', 'вытаскивать', 'настраивать', 'программировать', 'взламывать', 'атаковать', 'защищать', 'бежать', 'плыть', 'лететь', 'тренироваться', 'работать', 'учить', 'путешествовать', 'отдыхать', 'чистить', 'мыть', 'зеркалить', 'ветрить']

In [228]:
# Разные варианты как оцифровывать слово

def word_params_0(word):  # Дает 80 процентов правильных ответов
    return ord(word[0]), ord(word[-1]), len(word)

def word_params_1(word):  # Дает 83 процента правильных ответов
    return ord(word[0]), ord(word[1]), ord(word[-1]), ord(word[-2])

def word_params_2(word):  # Дает 82 процента правильных ответов
    return ord(word[0]), ord(word[1]), ord(word[2]), ord(word[-1]), ord(word[-2]), ord(word[-3])

def word_params_3(word):  # Дает 81 процент правильных ответов, ПОЧЕМУ ВСЕ МЕНЬШЕ И МЕНЬШЕ(((
    return ord(word[0]), ord(word[1]), ord(word[2]), ord(word[-1]), ord(word[-2]), ord(word[-3]), len(word)

def word_params_4(word):  # Дает 80 процентов правильных ответов
    return ord(word[0]), ord(word[-1]), ord(word[len(word)//2]), len(word)

def word_params_5(word):  # Дает 70 процентов правильных ответов
    return len(word),

max_len = max(len(w) for w in chain(nouns, verbs))
def word_params_6(word):
    # Хотел оцифровывать все буквы слова, но столкнулся с интересной проблемой:
    # Каждое слово имеет разныю длину, и непонятно как решать такую проблему
    params = [ord(c) for c in word]
    return params + [0] * (max_len - len(params))

word_params = word_params_0  # Выберем какой способ оцифровки использовать в последующих кубиках

In [229]:
from itertools import chain

X = Matrix(
    [
        [1] + list(word_params(w))
        for w in chain(nouns, verbs)
    ]
)

X

array([[   1, 1082, 1072,    5],
       [   1, 1089, 1083,    4],
       [   1, 1095, 1072,    5],
       [   1, 1088, 1072,    5],
       [   1, 1084, 1095,    3],
       [   1, 1087, 1086,    6],
       [   1, 1090, 1085,    7],
       [   1, 1094, 1082,    6],
       [   1, 1103, 1086,    6],
       [   1, 1082, 1096,    8],
       [   1, 1089, 1082,    6],
       [   1, 1082, 1088,    5],
       [   1, 1086, 1086,    4],
       [   1, 1089, 1072,    5],
       [   1, 1084, 1086,    6],
       [   1, 1089, 1072,    9],
       [   1, 1087, 1072,    7],
       [   1, 1088, 1072,    7],
       [   1, 1082, 1095,    4],
       [   1, 1083, 1072,    5],
       [   1, 1082, 1072,    5],
       [   1, 1089, 1072,    6],
       [   1, 1088, 1072,    4],
       [   1, 1074, 1072,    4],
       [   1, 1083, 1072,    5],
       [   1, 1074, 1072,    5],
       [   1, 1089, 1085,    6],
       [   1, 1082, 1086,    6],
       [   1, 1089, 1075,    5],
       [   1, 1082, 1072,    5],
       [  

In [230]:
Y = Matrix([[1]] * len(nouns) + [[0]] * len(verbs))
Y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [231]:
B = count_regression(X, Y)
B

array([[ 3.29377857e+01],
       [ 2.22380587e-03],
       [-3.16689731e-02],
       [-4.44689028e-02]])

In [232]:
# создадим новую выборку
nouns_2 = [
    "время", "человек", "год", "день", "вещь", "женщина", "жизнь", "ребенок",
    "мир", "школа", "государство", "семья", "студент", "группа", "страна",
    "проблема", "руководство", "программа", "вопрос", "работа", "слово",
    "место", "лицо", "друг", "глаз", "дом", "случай", "ребята", "система",
    "отношение", "город", "часть", "жена", "проект", "ночь", "деньги",
    "земля", "машина", "вода", "отец", "процесс", "музыка", "правительство",
    "номер", "политика", "парень", "путь", "новость", "информация", "театр",
    "армия", "наука", "роль", "состояние", "статья", "ситуация", "сердце",
    "смерть", "опыт", "результат", "искусство", "газета", "закон", "война",
    "голос", "развитие", "товарищ", "начальник", "тело", "учение", "мама",
    "мера", "улица", "вечер", "качество", "мысль", "дорога", "мать", "действие",
    "месяц", "государь", "язык", "любовь", "взгляд", "мама", "век", "школа",
    "цель", "общество", "деятельность", "организация", "президент", "комната",
    "автор", "здоровье", "хозяйство", "игра", "слово", "мнение", "документ"
]
verbs_2 = [
    "бежать", "видеть", "говорить", "думать", "жить", "знать", "играть", "идти",
    "искать", "кричать", "лететь", "любить", "мочь", "найти", "начать", "объяснять",
    "открывать", "петь", "писать", "плакать", "помнить", "работать", "решать",
    "сидеть", "слушать", "смеяться", "смотреть", "спать", "спрашивать", "стоять",
    "танцевать", "читать", "шутить", "прыгать", "учить", "показывать", "вести",
    "встречать", "выбирать", "готовить", "закрывать", "звонить", "игнорировать",
    "изучать", "класть", "менять", "мыть", "обедать", "обучать", "отвечать",
    "переводить", "плавать", "повторять", "поднимать", "покупать", "получать",
    "понимать", "посещать", "продавать", "разговаривать", "рассказывать", "рисовать",
    "собирать", "создавать", "сохранять", "строить", "требовать", "узнавать",
    "уходить", "фотографировать", "хотеть", "ценить", "чувствовать", "шить",
    "экспериментировать", "благодарить", "включать", "выключать", "выигрывать",
    "выполнять", "гарантировать", "дарить", "достигать", "забывать", "защищать",
    "инвестировать", "консультировать", "лечить", "наблюдать", "надеяться",
    "обсуждать", "отдыхать", "перемещать", "поддерживать", "предлагать",
    "принимать", "проектировать", "производить", "развивать", "рекомендовать",
    "сравнивать", "тренировать", "управлять", "финансировать", "хранить",
    "экономить", "бороться", "восхищаться", "вызывать", "доставлять", "запоминать",
    "изменять", "комментировать", "осуществлять", "переживать", "проходить",
    "улучшать", "формировать"
]

# Удалим дубли с прошлыми выборками
nouns_2 = [noun for noun in nouns_2 if noun not in nouns]
print(f'Новыя выборка существительных состоит из {len(nouns_2)} слов')
verbs_2 = [verb for verb in verbs_2 if verb not in verbs]
print(f'Новая выборка глаголов состоит из {len(verbs_2)} слов')

N = len(nouns_2) + len(verbs_2)
print(f'Разработанная модель будет протестирована на выборке из {N} слов')

X2 = Matrix(
    [
        [1] + list(word_params(word))
        for word in chain(nouns_2, verbs_2)
    ]
)
Y = X2 * B
ideal_Y = [1] * len(nouns_2) + [0] * len(verbs_2)

right_answers = 0
for yi, ideal_yi in zip(Y, ideal_Y):
    if ideal_yi == 1 and yi > 0.5 or ideal_yi == 0 and yi <= 0.5:
        right_answers += 1

print(f'Вероятность правильных ответов составила {round(right_answers / N * 100)}%')


Новыя выборка существительных состоит из 97 слов
Новая выборка глаголов состоит из 79 слов
Разработанная модель будет протестирована на выборке из 176 слов
Вероятность правильных ответов составила 80%
